import React from 'react';
import { jsPDF } from 'jspdf';
import { Download, FileText } from 'lucide-react';
import './ReportGenerator.css';

const ReportGenerator = ({ student, grades }) => {
  const generateReportCard = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(102, 126, 234);
    doc.text('LYCÉE DU MUHURA', 105, 20, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('STUDENT REPORT CARD', 105, 30, { align: 'center' });
    
    // Student Info
    doc.setFontSize(12);
    doc.text(`Student Name: ${student?.name || 'N/A'}`, 20, 45);
    doc.text(`Student ID: ${student?.studentId || 'N/A'}`, 20, 52);
    doc.text(`Class: ${student?.class || 'N/A'}`, 20, 59);
    doc.text(`Academic Year: 2023-2024`, 20, 66);
    
    // Grades Table
    doc.setFillColor(102, 126, 234);
    doc.rect(20, 75, 170, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text('Course', 25, 82);
    doc.text('Term', 80, 82);
    doc.text('Score', 110, 82);
    doc.text('Grade', 140, 82);
    doc.text('Status', 170, 82);
    
    // Grade Rows
    let y = 92;
    doc.setTextColor(0, 0, 0);
    
    grades?.forEach((grade, index) => {
      if (y > 250) {
        doc.addPage();
        y = 30;
      }
      
      // Alternate row colors
      if (index % 2 === 0) {
        doc.setFillColor(240, 240, 240);
        doc.rect(20, y - 5, 170, 10, 'F');
      }
      
      doc.text(grade?.course || 'N/A', 25, y);
      doc.text(grade?.term || 'N/A', 80, y);
      doc.text(`${grade?.score || 0}%`, 110, y);
      doc.text(grade?.grade || 'N/A', 140, y);
      doc.text(grade?.score >= 50 ? 'PASS' : 'FAIL', 170, y);
      
      y += 10;
    });
    
    // Summary
    y += 15;
    const totalScore = grades?.reduce((sum, g) => sum + (g?.score || 0), 0) || 0;
    const average = grades?.length ? (totalScore / grades.length).toFixed(1) : 0;
    
    doc.setFontSize(14);
    doc.setTextColor(102, 126, 234);
    doc.text('SUMMARY', 20, y);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Courses: ${grades?.length || 0}`, 20, y + 10);
    doc.text(`Average Score: ${average}%`, 20, y + 17);
    doc.text(`GPA: ${student?.gpa || 'N/A'}`, 20, y + 24);
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Lycée du Muhura School Management System', 105, 280, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 285, { align: 'center' });
    
    // Save
    doc.save(`${student?.name || 'Student'}_Report_Card.pdf`);
  };

  const generateTranscript = () => {
    const doc = new jsPDF('landscape');
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(102, 126, 234);
    doc.text('LYCÉE DU MUHURA - OFFICIAL TRANSCRIPT', 150, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Student: ${student?.name || 'N/A'}`, 20, 35);
    doc.text(`ID: ${student?.studentId || 'N/A'}`, 120, 35);
    doc.text(`Class: ${student?.class || 'N/A'}`, 200, 35);
    
    // Transcript Table
    doc.setFillColor(102, 126, 234);
    doc.rect(20, 45, 250, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text('Academic Year', 25, 52);
    doc.text('Course', 70, 52);
    doc.text('Credits', 120, 52);
    doc.text('Score', 150, 52);
    doc.text('Grade', 180, 52);
    doc.text('Points', 210, 52);
    doc.text('Status', 240, 52);
    
    let y = 62;
    doc.setTextColor(0, 0, 0);
    
    grades?.forEach((grade, index) => {
      if (y > 180) {
        doc.addPage();
        y = 30;
      }
      
      doc.text('2023-2024', 25, y);
      doc.text(grade?.course || 'N/A', 70, y);
      doc.text('3', 120, y);
      doc.text(`${grade?.score || 0}%`, 150, y);
      doc.text(grade?.grade || 'N/A', 180, y);
      doc.text(grade?.score >= 90 ? '4.0' : grade?.score >= 80 ? '3.0' : grade?.score >= 70 ? '2.0' : grade?.score >= 60 ? '1.0' : '0.0', 210, y);
      doc.text(grade?.score >= 50 ? 'PASS' : 'FAIL', 240, y);
      
      y += 8;
    });
    
    // Official Stamp
    doc.setDrawColor(102, 126, 234);
    doc.setLineWidth(2);
    doc.circle(230, 160, 25);
    doc.setFontSize(8);
    doc.setTextColor(102, 126, 234);
    doc.text('OFFICIAL', 230, 155, { align: 'center' });
    doc.text('SCHOOL SEAL', 230, 162, { align: 'center' });
    
    doc.save(`${student?.name || 'Student'}_Transcript.pdf`);
  };

  return (
    <div className="report-generator">
      <h3><FileText size={20} /> Generate Reports</h3>
      
      <div className="report-buttons">
        <button onClick={generateReportCard} className="report-btn primary">
          <Download size={16} />
          Report Card (PDF)
        </button>
        
        <button onClick={generateTranscript} className="report-btn secondary">
          <Download size={16} />
          Official Transcript
        </button>
      </div>
      
      <div className="report-preview">
        <h4>Preview</h4>
        <div className="preview-card">
          <div className="preview-header">
            <h5>LYCÉE DU MUHURA</h5>
            <p>Student Report</p>
          </div>
          <div className="preview-info">
            <p><strong>Name:</strong> {student?.name || 'N/A'}</p>
            <p><strong>ID:</strong> {student?.studentId || 'N/A'}</p>
            <p><strong>Class:</strong> {student?.class || 'N/A'}</p>
            <p><strong>Courses:</strong> {grades?.length || 0}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportGenerator;
